name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
jobs:
  check-changes:
      runs-on: ubuntu-latest
      outputs:
        backend_changed: ${{ steps.check_backend.outputs.backend_changed }}
        frontend_changed: ${{ steps.check_frontend.outputs.frontend_changed }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Check for backend changes
          id: check_backend
          run: |
            if git diff --name-only HEAD^ HEAD | grep -q '^backend/'; then
              echo "backend_changed=true" >> $GITHUB_ENV
              echo "::set-output name=backend_changed::true"
            else
              echo "backend_changed=false" >> $GITHUB_ENV
              echo "::set-output name=backend_changed::false"
            fi

        - name: Check for frontend changes
          id: check_frontend
          run: |
            if git diff --name-only HEAD^ HEAD | grep -q '^frontend/'; then
              echo "frontend_changed=true" >> $GITHUB_ENV
              echo "::set-output name=frontend_changed::true"
            else
              echo "frontend_changed=false" >> $GITHUB_ENV
              echo "::set-output name=frontend_changed::false"
            fi

  build-backend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.backend_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/movie-nodeapp-backend:latest

  build-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/movie-nodeapp-frontend:latest