name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-push-backend:
    if: ${{ contains(github.event.commits.*.added, 'backend/**') || contains(github.event.commits.*.modified, 'backend/**') || contains(github.event.commits.*.renamed, 'backend/**') || contains(github.event.commits.*.removed, 'backend/**') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/movie-nodeapp-backend:latest

  build-push-frontend:
    if: ${{ contains(github.event.commits.*.added, 'frontend/**') || contains(github.event.commits.*.modified, 'frontend/**') || contains(github.event.commits.*.renamed, 'frontend/**') || contains(github.event.commits.*.removed, 'frontend/**') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/movie-nodeapp-backend:latest